import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// 전역 폰트
const inter = Inter({ subsets: ['latin'] })
// 앱 메타데이터 정의
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// 모든 페이지의 기본 레이아웃 정의
export default function RootLayout({
  children, // prop 을 받아와서 레이아웃 내에 렌더링한다.
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <div>layout입니다</div>
      {children}
    </body>
    </html>
  )
}
